### PR TITLE
Adds generic install instructions for Linux

### PR DESCRIPTION
**Pull request by davorb**
This makes it a little bit clearer for new users, who are not familiar with Pidgin plugins.

### CODE REVIEW

**Comment by EionRobb** [comment]
Thanks :)

**Comment by xvitaly** [comment]
On some distributions plugins will not work from ~/.purple/plugins/.

**Comment by davorb** [comment]
@xvitaly Really? That seems really weird. Why would that be?

In any case, it's a good starting point for someone who just wants to get the thing up and running, and doesn't want to spend too much time fiddling with it. It's all about minimising friction for the end users...

**Comment by xvitaly** [comment]
> Really? That seems really weird. Why would that be?

This depends of maintainer of Pidgin package.

> In any case, it's a good starting point for someone who just wants to get the thing up and running, and doesn't want to spend too much time fiddling with it. It's all about minimising friction for the end users...

End users should install package from repository. Binary dynamically linked plugins is bad way.

**Comment by davorb** [comment]
@xvitaly I agree with your points.

**Pull request merged**
