### PR TITLE
Added SPEC file

### PR DESCRIPTION
**Pull request by xvitaly**
Added SPEC file for Fedora/openSUSE/RHEL/CentOS.

### CODE REVIEW

**Comment by EionRobb** [comment]
Do you think you could update the spec to reflect that the build requires gnome-keyring-devel, but the actual running of the plugin does not, as this is an optional runtime dependency if the user is using telepathy-haze

**Comment by xvitaly** [comment]
Gnome-keyring-devel is required. If you want to remove it, you should remove gnome-keyring-1 from LIBPURPLE_CFLAGS.

**Comment by EionRobb** [comment]
Yes, required to build, not to run

**Comment by xvitaly** [comment]
Ok. I will fix SPEC now.

**Comment by xvitaly** [comment]
Fixed.

**Comment by EionRobb** [comment]
Awesome, thanks :) 
I realise its a bit of a strange situation, but such is required for Empathy

**Pull request merged**
